import React from "react";
import {} from 'react-native'

const Colors = {
    'indianRed'         : '#CD5C5C',
    'mediumPurple'      : '#9370DB',
    'violetPurple'      : '#EE82EE',
    'Pink'              : '#FFC0CB',
    'LightPink'         : '#FFB6C1',	
    'HotPink'           : '#FF69B4',
    'DeepPink'          : '#FF1493',
    'MediumVioletRed'   : '#C71585',	
    'PaleVioletRed'     : '#DB7093',
    'ThistlePurple'	    : '#D8BFD8',
    'SlateBlue'	        : '#6A5ACD',
    'DarkSlateBlue'	    : '#483D8B',
    'MediumSlateBlue'	: '#7B68EE',
    'GreenYellow'	    : '#ADFF2F',
    'Chartreuse'        : '#7FFF00',
    'LawnGreen'         : '#7CFC00',
    'Lime'              : '#00FF00',
    'LimeGreen'         : '#32CD32',
    'PaleGreen'         : '#98FB98',
    'LightGreen'     	: '#90EE90',
    'MediumSpringGreen' : '#00FA9A',
    'SpringGreen'       : '#00FF7F',
    'MediumSeaGreen'    : '#3CB371',
    'SeaGreen'	        :'#2E8B57',
    'ForestGreen'       : '#228B22',
    'Green'             : '#008000',
    'DarkGreen'         : '#006400',
    'YellowGreen'       : '#9ACD32',
    'OliveDrab'         : '#6B8E23',
    'Olive'	            :' #808000',
    'DarkOliveGreen'	:' #556B2F',
    'MediumAquamarine'  : '#66CDAA',
    'DarkSeaGreen'      : '#8FBC8B',
    'LightSeaGreen'     : '#20B2AA',
    'DarkCyan'          : '#008B8B',
    'Teal'              : '#008080',
    'LightSteelBlue'	: '#B0C4DE',
    'CornflowerBlue'	: '#6495ED',
    'LightSlateGray'	: '#778899',
    'purple'            : '#D4A1FE',
}

export default Colors